/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3291dcad-43c7-448b-9be6-e6f9f7ec8bb9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Zzx1VCIPJ",
    "aws_user_pools_web_client_id": "4lca0862jre9698op2ss24eupl",
    "oauth": {}
};


export default awsmobile;
